---
output: html_document
---

## Setup

```{r setup, message = FALSE}
library(tidyverse)
library(tidymodels)
```

## Data

```{r}
hotels = read_csv(
  'https://tidymodels.org/start/case-study/hotels.csv'
) %>%
  mutate(
    across(where(is.character), as.factor)
  )
```

## Test train split

```{r}
set.seed(123)

splits = initial_split(hotels, strata = children)

hotel_train = training(splits)
hotel_test = testing(splits)
```


## k-Fold

```{r}
hotel_vf = rsample::vfold_cv(hotel_train, v=5, strata = children)
```

## Random Forest

```{r}
rf_model = rand_forest(mtry = tune(), min_n = tune(), trees = 100) %>% 
  set_engine("ranger", num.threads = 8) %>% 
  set_mode("classification")

rf_recipe = recipe(children ~ ., data = hotel_train) %>% 
  step_date(arrival_date) %>% 
  step_holiday(arrival_date) %>% 
  step_rm(arrival_date)

rf_work = workflow() %>% 
  add_model(rf_model) %>% 
  add_recipe(rf_recipe)

rf_model %>%
  parameters()

rf_res = rf_work %>% 
  tune_grid(
    hotel_vf,
    grid = 10,
    control = control_grid(save_pred = TRUE),
    metrics = metric_set(roc_auc)
  )
```

```{r}
rf_res %>% 
  show_best(metric = "roc_auc")

autoplot(rf_res)
```

```{r}
rf_best = rf_res %>%
  select_best(metric = "roc_auc")

rf_best_pred = rf_res %>%
  collect_predictions(parameters = rf_best)
```

```{r}
rf_work_tuned = update_model(
  rf_work, 
  rand_forest(
    trees=100,
    mtry = rf_best$mtry, 
    min_n = rf_best$min_n
  ) %>%
    set_engine("ranger", num.threads = 8)
)

rf_fit = rf_work_tuned %>%
  fit(data=hotel_train)
```


## Compare

```{r}

bind_rows(
  lr_val_fit %>%
    collect_predictions() %>%
    roc_curve(children, .pred_children) %>% 
    mutate(model = "glm"),
  lasso_best_pred %>%
    roc_curve(children, .pred_children) %>%
    mutate(model = "Lasso (glmnet)"),
  rf_best_pred %>% 
    roc_curve(children, .pred_children) %>%
    mutate(model = "Random Forest (ranger)")
) %>%
  ggplot(aes(x=1-specificity, y=sensitivity, col=model)) +
    geom_path() + 
    geom_abline(lty = 3) +
    coord_equal()
```
